#!/usr/bin/env python3
"""
Script to download and parse AS numbers from Anapaya documentation.
"""

import requests
from bs4 import BeautifulSoup
import sys

url = "https://learn.anapaya.net/docs/resources/assignments/ases/"
output_file = "chrome/src/popup/autonomous_system.ts"

def download_webpage(url):
    try:
        headers = {
            'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        return response.text
    except requests.RequestException as e:
        print(f"Error downloading webpage: {e}")
        sys.exit(1)

def parse_as_data(html_content):
    soup = BeautifulSoup(html_content, 'html.parser')

    table = soup.find('table')

    if not table:
        print("Could not find AS table")
        sys.exit(1)
    
    as_map = {}
    tbody = table.find('tbody')
    if tbody:
        for row in tbody.find_all('tr'):
            cells = row.find_all('td')
            if len(cells) >= 2:
                # Extract AS number from first cell
                as_number = cells[0].get_text().strip()

                # Extract organization name from second cell
                org_name = cells[1].get_text().strip()

                if as_number and org_name:
                    as_map[as_number] = org_name
    
    return as_map

def get_enum_name(as_number):
    return f"AS_{as_number.replace(':', '_')}"

def generate_ts_snippet(as_map):
    sorted_items = sorted(as_map.items(), key=lambda x: int(x[0]) if x[0].isdigit() else float('inf'))

    # generating the enum
    ts_content = "// The contents of this file are autogenerated. Any modifications made\n"
    ts_content += "// will be overwritten when the \"retrieve_as_map.py\" script is executed.\n\n"

    ts_content += "/**\n"
    ts_content += " * An enum containing all autonomous systems.\n"
    ts_content += " */\n"
    ts_content += "export enum AutonomousSystem {\n"
    for (as_number, _) in sorted_items:
        enum_name = get_enum_name(as_number)
        ts_content += f"\t{enum_name} = \"{as_number}\",\n"
    ts_content += "\tAS_UNKNOWN = \"UNKNOWN\",\n"
    ts_content += "}\n\n"

    # generating the map that maps enum entries to names
    ts_content += "/**\n"
    ts_content += " * A map that maps {@link AutonomousSystem} entries to their corresponding name.\n"
    ts_content += " */\n"
    ts_content += "export const asNameMap: Record<AutonomousSystem, string> = {\n"
    for i, (as_number, name) in enumerate(sorted_items):
        enum_name = get_enum_name(as_number)
        escaped_name = name.replace('"', '\\"')
        ts_content += f'\t[AutonomousSystem.{enum_name}]: "{escaped_name}",\n'
    ts_content += "\t[AutonomousSystem.AS_UNKNOWN]: \"UNKNOWN\",\n"
    ts_content += "};"
    return ts_content

def main():
    print(f"Downloading webpage from: {url}")
    html_content = download_webpage(url)
    
    print("Parsing AS data...")
    as_map = parse_as_data(html_content)
    if not as_map:
        print("No AS data found")
        sys.exit(1)
    
    print(f"Found {len(as_map)} AS entries")
    
    ts_snippet = generate_ts_snippet(as_map)

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(ts_snippet)
    
    print(f"TypeScript snippet written to: {output_file}")
    

if __name__ == "__main__":
    main()