#!/usr/bin/env python3
"""
Script to download and parse Country Codes from wikipedia.
"""

import requests
from bs4 import BeautifulSoup
import sys

url = "https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2"
output_file = "chrome/src/popup/country_code.ts"

def download_webpage(url):
    try:
        headers = {
            'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        return response.text
    except requests.RequestException as e:
        print(f"Error downloading webpage: {e}")
        sys.exit(1)

def parse_as_data(html_content):
    soup = BeautifulSoup(html_content, 'html.parser')

    official_assignments_section = None
    for h3 in soup.find_all('h3'):
        if "Officially assigned code elements" in h3.get_text():
            official_assignments_section = h3
            break

    if not official_assignments_section:
        print("No official assignments section found")
        sys.exit(1)

    table = official_assignments_section.find_next('table')

    if not table:
        print("Could not find assignments table")
        sys.exit(1)

    # maps the (usually) 2-character country code to their description, example entry: "CH": "Switzerland"
    country_code_map = {}
    tbody = table.find('tbody')
    if tbody:
        for row in tbody.find_all('tr'):
            cells = row.find_all('td')
            if len(cells) >= 2:
                # extract country code from first cell
                country_code_element = cells[0].find('a')
                if country_code_element:
                    country_code = country_code_element.get_text().strip()

                    # extract country name from second cell
                    country_name_element = cells[1].find('a')
                    if country_name_element:
                        country_name = country_name_element.get_text().strip()

                        # add to map
                        if country_code and country_name:
                            country_code_map[country_code] = country_name

    return country_code_map

def generate_ts_snippet(country_code_map):
    ts_content = "// The contents of this file are autogenerated. Any modifications made\n"
    ts_content += "// will be overwritten when the \"retrieve_country_code.py\" script is executed.\n\n"

    # generating the enum
    ts_content += "/**\n"
    ts_content += " * An enum containing all country codes.\n"
    ts_content += " *\n"
    ts_content += " * The values are retrieved using the \"retrieve_country_codes.py\" script from https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2.\n"
    ts_content += " */\n"
    ts_content += "export enum CountryCode {\n"
    for country_code, country_name in country_code_map.items():
        # adding a comment to display the country's name that the code represents
        ts_content += f"\t/** {country_name} */\n"
        ts_content += f"\t{country_code} = \"{country_code}\",\n"
    ts_content += "}\n"

    return ts_content

def main():
    print(f"Downloading webpage from: {url}")
    html_content = download_webpage(url)

    print("Parsing Country Code data...")
    country_code_map = parse_as_data(html_content)
    if not country_code_map:
        print("No Country Code data found")
        sys.exit(1)

    print(f"Found {len(country_code_map)} Country Code entries")

    ts_snippet = generate_ts_snippet(country_code_map)

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(ts_snippet)

    print(f"TypeScript snippet written to: {output_file}")


if __name__ == "__main__":
    main()