import {asNameMap, AutonomousSystem} from "./autonomous_system.js";
import {CountryCode} from "./country_code.js";

/**
 * Returns the name of the AS specified by {@link as}.
 */
export function getASName(as: AutonomousSystem) {
    return asNameMap[as];
}

/**
 * Converts a string into its corresponding {@link AutonomousSystem} enum entry representation.
 * If {@link AutonomousSystem} does not contain a corresponding entry, {@link AutonomousSystem.AS_UNKNOWN} is returned instead.
 */
export function toAutonomousSystem(value: string) {
    return Object.values(AutonomousSystem).includes(value as AutonomousSystem)
        ? value as AutonomousSystem
        : AutonomousSystem.AS_UNKNOWN;
}

/**
 * Maps an {@link AutonomousSystem} to the {@link CountryCode} of the country in which the AS's entity resides.
 *
 * If for an entry it was evident, that no single country can be assigned, {@link CountryCode.UNKNOWN} is assigned.
 */
export const asCountryMap: Record<AutonomousSystem, CountryCode> = {
    [AutonomousSystem.AS_88]: CountryCode.US,
    [AutonomousSystem.AS_225]: CountryCode.US,
    [AutonomousSystem.AS_559]: CountryCode.CH,
    [AutonomousSystem.AS_1125]: CountryCode.NL,
    [AutonomousSystem.AS_1140]: CountryCode.NL,
    [AutonomousSystem.AS_1349]: CountryCode.GB,
    [AutonomousSystem.AS_1888]: CountryCode.NL,
    [AutonomousSystem.AS_1916]: CountryCode.BR,
    [AutonomousSystem.AS_2546]: CountryCode.GR,
    [AutonomousSystem.AS_3303]: CountryCode.CH,
    [AutonomousSystem.AS_3786]: CountryCode.KR,
    [AutonomousSystem.AS_4158]: CountryCode.HK,
    [AutonomousSystem.AS_6730]: CountryCode.CH,
    [AutonomousSystem.AS_8300]: CountryCode.CH,
    [AutonomousSystem.AS_8883]: CountryCode.CH,
    [AutonomousSystem.AS_9025]: CountryCode.CH,
    [AutonomousSystem.AS_12350]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_12387]: CountryCode.CH,
    [AutonomousSystem.AS_12429]: CountryCode.CH,
    [AutonomousSystem.AS_12511]: CountryCode.CH,
    [AutonomousSystem.AS_12649]: CountryCode.CH,
    [AutonomousSystem.AS_12928]: CountryCode.CH,
    [AutonomousSystem.AS_13030]: CountryCode.CH,
    [AutonomousSystem.AS_13267]: CountryCode.CH,
    [AutonomousSystem.AS_13282]: CountryCode.CH,
    [AutonomousSystem.AS_13283]: CountryCode.CH,
    [AutonomousSystem.AS_15361]: CountryCode.CH,
    [AutonomousSystem.AS_15532]: CountryCode.CH,
    [AutonomousSystem.AS_15623]: CountryCode.CH,
    [AutonomousSystem.AS_20965]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_21047]: CountryCode.DE,
    [AutonomousSystem.AS_24951]: CountryCode.CH,
    [AutonomousSystem.AS_25090]: CountryCode.CH,
    [AutonomousSystem.AS_25289]: CountryCode.CH,
    [AutonomousSystem.AS_28928]: CountryCode.CH,
    [AutonomousSystem.AS_29641]: CountryCode.DE,
    [AutonomousSystem.AS_30870]: CountryCode.NL,
    [AutonomousSystem.AS_31004]: CountryCode.CH,
    [AutonomousSystem.AS_31097]: CountryCode.CH,
    [AutonomousSystem.AS_33965]: CountryCode.CH,
    [AutonomousSystem.AS_35240]: CountryCode.CH,
    [AutonomousSystem.AS_39932]: CountryCode.CH,
    [AutonomousSystem.AS_41623]: CountryCode.CH,
    [AutonomousSystem.AS_41632]: CountryCode.CH,
    [AutonomousSystem.AS_43577]: CountryCode.CH,
    [AutonomousSystem.AS_44346]: CountryCode.CH,
    [AutonomousSystem.AS_46646]: CountryCode.CH,
    [AutonomousSystem.AS_47176]: CountryCode.CH,
    [AutonomousSystem.AS_48038]: CountryCode.CH,
    [AutonomousSystem.AS_50999]: CountryCode.SA,
    [AutonomousSystem.AS_57676]: CountryCode.CH,
    [AutonomousSystem.AS_57965]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_59414]: CountryCode.CH,
    [AutonomousSystem.AS_59647]: CountryCode.CH,
    [AutonomousSystem.AS_60284]: CountryCode.CH,
    [AutonomousSystem.AS_64580]: CountryCode.CH,
    [AutonomousSystem.AS_196722]: CountryCode.CH,
    [AutonomousSystem.AS_197312]: CountryCode.CH,
    [AutonomousSystem.AS_200888]: CountryCode.CH,
    [AutonomousSystem.AS_202405]: CountryCode.LI,
    [AutonomousSystem.AS_202908]: CountryCode.LI,
    [AutonomousSystem.AS_203311]: CountryCode.EE,
    [AutonomousSystem.AS_205755]: CountryCode.NL,
    [AutonomousSystem.AS_206662]: CountryCode.CH,
    [AutonomousSystem.AS_208305]: CountryCode.CH,
    [AutonomousSystem.AS_208836]: CountryCode.CH,
    [AutonomousSystem.AS_210018]: CountryCode.CH,
    [AutonomousSystem.AS_212777]: CountryCode.CH,
    [AutonomousSystem.AS_216434]: CountryCode.CH,
    [AutonomousSystem.AS_401500]: CountryCode.US,

    [AutonomousSystem.AS_2_0_0]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_1]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_2]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_3]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_4]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_5]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_6]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_7]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_8]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_9]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_a]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_b]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_c]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_d]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_e]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_f]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_10]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_11]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_12]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_13]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_14]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_15]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_16]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_17]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_18]: CountryCode.SG,
    [AutonomousSystem.AS_2_0_19]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_1a]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_1b]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_1c]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_1d]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_1e]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_1f]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_20]: CountryCode.LU,
    [AutonomousSystem.AS_2_0_21]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_22]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_23]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_24]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_25]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_26]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_27]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_28]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_29]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_2a]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_2b]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_2c]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_2d]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_2e]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_2f]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_30]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_33]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_34]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_35]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_36]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_37]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_38]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_39]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_3a]: CountryCode.US,
    // KREONET Seoul
    [AutonomousSystem.AS_2_0_3b]: CountryCode.KR,
    // KREONET Hong Kong
    [AutonomousSystem.AS_2_0_3c]: CountryCode.HK,
    // KREONET Singapore
    [AutonomousSystem.AS_2_0_3d]: CountryCode.SG,
    // KREONET Amsterdam
    [AutonomousSystem.AS_2_0_3e]: CountryCode.NL,
    // KREONET Chicago
    [AutonomousSystem.AS_2_0_3f]: CountryCode.US,
    // KREONET Seattle
    [AutonomousSystem.AS_2_0_40]: CountryCode.US,
    [AutonomousSystem.AS_2_0_41]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_42]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_43]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_44]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_45]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_46]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_47]: CountryCode.US,
    [AutonomousSystem.AS_2_0_48]: CountryCode.US,
    [AutonomousSystem.AS_2_0_49]: CountryCode.EE,
    [AutonomousSystem.AS_2_0_4a]: CountryCode.DE,
    [AutonomousSystem.AS_2_0_4b]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_4c]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_4d]: CountryCode.KR,
    [AutonomousSystem.AS_2_0_4f]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_50]: CountryCode.IE,
    [AutonomousSystem.AS_2_0_51]: CountryCode.FR,
    [AutonomousSystem.AS_2_0_53]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_54]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_55]: CountryCode.FR,
    [AutonomousSystem.AS_2_0_56]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_57]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_58]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_59]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_5a]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_5b]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_5c]: CountryCode.BR,
    [AutonomousSystem.AS_2_0_5d]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_5e]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_5f]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_60]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_61]: CountryCode.SG,
    [AutonomousSystem.AS_2_0_63]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_64]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_65]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_66]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_67]: CountryCode.NL,
    [AutonomousSystem.AS_2_0_68]: CountryCode.GB,
    [AutonomousSystem.AS_2_0_69]: CountryCode.DE,
    [AutonomousSystem.AS_2_0_6a]: CountryCode.GB,
    [AutonomousSystem.AS_2_0_6b]: CountryCode.DE,
    [AutonomousSystem.AS_2_0_6c]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_6d]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_6e]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_6f]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_70]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_71]: CountryCode.FR,
    [AutonomousSystem.AS_2_0_72]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_73]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_74]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_75]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_76]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_77]: CountryCode.US,
    [AutonomousSystem.AS_2_0_78]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_79]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_7a]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_7b]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_7c]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_7d]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_7e]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_7f]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_80]: CountryCode.US,
    [AutonomousSystem.AS_2_0_81]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_82]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_83]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_84]: CountryCode.AU,
    [AutonomousSystem.AS_2_0_85]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_86]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_87]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_88]: CountryCode.US,
    [AutonomousSystem.AS_2_0_89]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_8a]: CountryCode.TO_BE_DETERMINED,
    [AutonomousSystem.AS_2_0_8b]: CountryCode.US,
    [AutonomousSystem.AS_2_0_8c]: CountryCode.US,
    [AutonomousSystem.AS_2_0_8d]: CountryCode.US,
    [AutonomousSystem.AS_2_0_8e]: CountryCode.US,
    [AutonomousSystem.AS_2_0_8f]: CountryCode.US,
    [AutonomousSystem.AS_2_0_90]: CountryCode.US,
    [AutonomousSystem.AS_2_0_91]: CountryCode.US,
    [AutonomousSystem.AS_2_0_92]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_96]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_97]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_98]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_99]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_9a]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_9b]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_9c]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_9d]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_9e]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_9f]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_a0]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_a1]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_a2]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_a3]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_a4]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_a5]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_a6]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_a8]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_a9]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_aa]: CountryCode.US,
    [AutonomousSystem.AS_2_0_ab]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_ac]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_ad]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_ae]: CountryCode.NL,
    [AutonomousSystem.AS_2_0_af]: CountryCode.US,
    [AutonomousSystem.AS_2_0_b1]: CountryCode.NL,
    [AutonomousSystem.AS_2_0_b2]: CountryCode.NL,
    [AutonomousSystem.AS_2_0_130]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_131]: CountryCode.US,
    [AutonomousSystem.AS_2_0_132]: CountryCode.FR,
    [AutonomousSystem.AS_2_0_133]: CountryCode.FR,
    [AutonomousSystem.AS_2_0_134]: CountryCode.DE,
    [AutonomousSystem.AS_2_0_135]: CountryCode.DE,
    [AutonomousSystem.AS_2_0_136]: CountryCode.CA,
    [AutonomousSystem.AS_2_0_137]: CountryCode.CA,
    [AutonomousSystem.AS_2_0_138]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_139]: CountryCode.UNKNOWN,
    [AutonomousSystem.AS_2_0_13a]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_13b]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_13c]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_13d]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_13e]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_13f]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_140]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_141]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_142]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_143]: CountryCode.US,
    [AutonomousSystem.AS_2_0_144]: CountryCode.FR,
    [AutonomousSystem.AS_2_0_145]: CountryCode.SG,
    [AutonomousSystem.AS_2_0_146]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_147]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_148]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_149]: CountryCode.NL,
    [AutonomousSystem.AS_2_0_14a]: CountryCode.NL,
    [AutonomousSystem.AS_2_0_14b]: CountryCode.US,
    [AutonomousSystem.AS_2_0_14c]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_14d]: CountryCode.US,
    [AutonomousSystem.AS_2_0_14e]: CountryCode.GB,
    [AutonomousSystem.AS_2_0_14f]: CountryCode.DE,
    [AutonomousSystem.AS_2_0_150]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_151]: CountryCode.SG,
    [AutonomousSystem.AS_2_0_152]: CountryCode.BR,
    [AutonomousSystem.AS_2_0_153]: CountryCode.CH,
    [AutonomousSystem.AS_2_0_154]: CountryCode.BE,
    [AutonomousSystem.AS_2_0_155]: CountryCode.US,
    [AutonomousSystem.AS_2_0_156]: CountryCode.DE,
    [AutonomousSystem.AS_2_0_157]: CountryCode.AT,
    [AutonomousSystem.AS_2_0_158]: CountryCode.CH,
    [AutonomousSystem.AS_UNKNOWN]: CountryCode.UNKNOWN,
};